// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OYMSmArM97yx_SBZFcaD0bWrOS4x1uc',
    appId: '1:887260997035:web:23ef59c80c2e0167949eee',
    messagingSenderId: '887260997035',
    projectId: 'medigo-211e8',
    authDomain: 'medigo-211e8.firebaseapp.com',
    storageBucket: 'medigo-211e8.firebasestorage.app',
    measurementId: 'G-GWNRDD2BWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz74F_6DI28XzutITz3zSqJk7UfQsof8Y',
    appId: '1:887260997035:android:68db717146a07d1a949eee',
    messagingSenderId: '887260997035',
    projectId: 'medigo-211e8',
    storageBucket: 'medigo-211e8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3OYMSmArM97yx_SBZFcaD0bWrOS4x1uc',
    appId: '1:887260997035:web:de62fab52f8ff017949eee',
    messagingSenderId: '887260997035',
    projectId: 'medigo-211e8',
    authDomain: 'medigo-211e8.firebaseapp.com',
    storageBucket: 'medigo-211e8.firebasestorage.app',
    measurementId: 'G-MW8T5VGSXX',
  );
}
